/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mouth.glb -t 
Author: Russian guy (https://sketchfab.com/Russian_Guy2007)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/mouth-0c029ae733e94cf9ad1a486c7748fe42
Title: Mouth
*/
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import React, { useRef, useMemo } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, Html } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'
import { useControls } from 'leva'

function CavityHole({ activeTreatment }: { activeTreatment?: number | null }) {
  const materialRef = useRef<THREE.ShaderMaterial>(null);
  const meshRef = useRef<THREE.Mesh>(null);

  useFrame((state, delta) => {
    if (!materialRef.current || !meshRef.current) return;
    
    const targetOpacity = activeTreatment === 0 ? 0.9 : 0;
    materialRef.current.uniforms.uOpacity.value = THREE.MathUtils.lerp(
      materialRef.current.uniforms.uOpacity.value,
      targetOpacity,
      delta * 5
    );

    meshRef.current.visible = materialRef.current.uniforms.uOpacity.value > 0.01;
  });

  return (
    <mesh 
      ref={meshRef} 
      position={[0.52, -0.52, 0.23]} 
      rotation={[-2.4, 0.01, 2.08]}
    >
      {/* Size increased from 0.07 to 0.11 */}
      <circleGeometry args={[0.11, 32]} />
      <shaderMaterial 
        ref={materialRef}
        transparent
        depthWrite={false}
        side={THREE.DoubleSide}
        polygonOffset
        polygonOffsetFactor={-10}
        uniforms={{
          uOpacity: { value: 0 }
        }}
        vertexShader={`
          varying vec2 vUv;
          void main() {
            vUv = uv;
            gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
          }
        `}
        fragmentShader={`
          uniform float uOpacity;
          varying vec2 vUv;

          // Simple pseudo-random function for porosity
          float rand(vec2 co){
              return fract(sin(dot(co.xy ,vec2(12.9898,78.233))) * 43758.5453);
          }

          void main() {
            vec2 center = vec2(0.5, 0.5);
            float dist = distance(vUv, center);
            
            float angle = atan(vUv.y - 0.5, vUv.x - 0.5);
            
            // Organic, asymmetrical blob shape
            float baseRadius = 0.25;
            float shapeNoise = 0.06 * sin(angle * 2.0) + 0.04 * cos(angle * 3.5) + 0.02 * sin(angle * 6.0);
            float radius = baseRadius + shapeNoise;
            
            // Very soft gradient at the edge to blend seamlessly with enamel
            float alpha = smoothstep(radius + 0.08, radius - 0.1, dist);
            
            // Colors: Enamel stain (yellowish-brown) -> Deep decay (black)
            vec3 stainColor = vec3(0.35, 0.18, 0.05); 
            vec3 deepDecay = vec3(0.01, 0.0, 0.0);
            
            // Sharper transition to pitch black
            vec3 color = mix(stainColor, deepDecay, smoothstep(radius - 0.02, radius - 0.15, dist));
            
            // FAKE 3D INDENTATION (Creates a bevel/rim illusion)
            // Slope vector pointing inward
            vec2 toCenter = normalize(center - vUv);
            vec2 lightDir = normalize(vec2(1.0, 1.0)); // Simulated light direction
            float fakeLight = dot(toCenter, lightDir);
            
            // Apply lighting only on the rim (slope), not in the deep black center
            float rimArea = smoothstep(0.0, radius, dist); 
            // Highlight one side of the rim, shadow the other
            color += vec3(0.15, 0.1, 0.05) * fakeLight * rimArea * 2.0;
            
            // Add slight static noise to make it look porous like rotten dentin
            float porosity = rand(vUv * 200.0) * 0.1;
            color -= porosity;
            
            gl_FragColor = vec4(color, alpha * uOpacity);
          }
        `}
      />
    </mesh>
  );
}

function PeriodontitisEffect({ activeTreatment }: { activeTreatment?: number | null }) {
  const materialRef = useRef<THREE.ShaderMaterial>(null);
  const meshRef = useRef<THREE.Mesh>(null);
  
  // Periodontitis slider has been permanently removed!
  const periodontitisParams = {
    px: 0.00,
    py: -0.84,
    pz: -0.85,
    rx: 1.35,
    ry: 0.04,
    rz: 0.03, // Reverted rotation back to original perfect setting
    sx: 0.85,
    sy: 0.18,
    sz: 1.01,
  };
  
  useFrame((state, delta) => {
    if (!materialRef.current || !meshRef.current) return;
    const targetOpacity = activeTreatment === 1 ? 0.95 : 0;
    materialRef.current.uniforms.uOpacity.value = THREE.MathUtils.lerp(
      materialRef.current.uniforms.uOpacity.value,
      targetOpacity,
      delta * 5
    );
    meshRef.current.visible = materialRef.current.uniforms.uOpacity.value > 0.01;
  });

  return (
    <mesh 
      ref={meshRef}
      position={[periodontitisParams.px, periodontitisParams.py, periodontitisParams.pz]} 
      rotation={[periodontitisParams.rx, periodontitisParams.ry, periodontitisParams.rz]} 
      scale={[periodontitisParams.sx, periodontitisParams.sy, periodontitisParams.sz]} 
    >
      <planeGeometry args={[1, 1, 64, 32]} />
      <shaderMaterial 
        ref={materialRef}
        transparent
        depthWrite={false}
        polygonOffset
        polygonOffsetFactor={-10}
        side={THREE.DoubleSide}
        uniforms={{
          uOpacity: { value: 0 }
        }}
        vertexShader={`
          varying vec2 vUv;
          void main() {
            vUv = uv;
            vec3 pos = position;
            
            // Curve wraps nicely around the jaw (Z axis)
            float curveZ = pow(abs(pos.x), 2.0) * 0.3; 
            
            // Base symmetric upward curve
            float curveY = pow(abs(pos.x), 2.0) * 2.0;
            
            // Extra upward curve ONLY for the right side (pos.x > 0)
            if (pos.x > 0.0) {
              curveY += pow(pos.x, 2.0) * 2.5; // Strong boost for right side
            }
            
            pos.z -= curveZ;
            pos.y += curveY;
            
            gl_Position = projectionMatrix * modelViewMatrix * vec4(pos, 1.0);
          }
        `}
        fragmentShader={`
          varying vec2 vUv;
          uniform float uOpacity;
          
          // Simple hash for noise
          float hash(vec2 p) {
            p = fract(p * vec2(123.34, 456.21));
            p += dot(p, p + 45.32);
            return fract(p.x * p.y);
          }
          
          // Smooth noise function
          float smoothNoise(vec2 p) {
            vec2 i = floor(p);
            vec2 f = fract(p);
            f = f * f * (3.0 - 2.0 * f);
            float a = hash(i);
            float b = hash(i + vec2(1.0, 0.0));
            float c = hash(i + vec2(0.0, 1.0));
            float d = hash(i + vec2(1.0, 1.0));
            return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
          }
          
          // Fractal noise
          float fbm(vec2 p) {
            float f = 0.0;
            float amp = 0.5;
            for(int i = 0; i < 4; i++) {
              f += amp * smoothNoise(p);
              p *= 2.0;
              amp *= 0.5;
            }
            return f;
          }

          void main() {
             float n = fbm(vUv * 25.0);
             
             // 8 peaks to match gaps between ~8 teeth
             float arches = abs(sin(vUv.x * 3.14159 * 8.0));
             
             // Tartar line varies based on the arches
             float tartarLine = 0.35 + 0.15 * (1.0 - arches);
             float topEdge = 0.65 + 0.3 * (1.0 - arches);
             
             // FADE EDGES FOR FLAWLESS BLENDING
             // Horizontal fade so it doesn't have sharp left/right edges
             float edgeFade = smoothstep(0.0, 0.25, vUv.x) * smoothstep(1.0, 0.75, vUv.x);
             
             // Vertical fade for the gums. 
             // We start completely transparent at the bottom (0.0) and fade in the red inflammation right below the tartar.
             float gumFade = smoothstep(0.05, tartarLine - 0.05, vUv.y);
             
             // Fade the top edge into the teeth
             float topFade = smoothstep(topEdge + 0.05, topEdge - 0.1, vUv.y);
             
             float alpha = gumFade * topFade * edgeFade * uOpacity;
             
             // 1. INFLAMED GUMS
             // Deep, angry red for severe periodontitis. No need for "natural gum" color because we just use alpha fade to blend with the real model's gums.
             vec3 gumColor = vec3(0.65, 0.1, 0.15); 
             // Add slight brightness variation for swelling
             gumColor += vec3(0.1, 0.0, 0.0) * smoothstep(0.3, 0.8, fbm(vUv * 15.0));
             
             // 2. GOLDEN/BROWN TARTAR
             vec3 tartarBase = mix(vec3(0.75, 0.65, 0.3), vec3(0.3, 0.2, 0.05), n);
             // White/calcified plaque spots
             tartarBase += vec3(0.8, 0.8, 0.7) * smoothstep(0.65, 0.9, n) * 0.7;
             // Fake specular highlight for a wet/crusty look
             tartarBase += vec3(1.0, 0.9, 0.8) * pow(n, 5.0) * 0.3;
             
             // Mix gums and tartar
             float tartarMix = smoothstep(tartarLine - 0.03, tartarLine + 0.01, vUv.y);
             vec3 finalColor = mix(gumColor, tartarBase, tartarMix);
             
             // Fake AO shadow below the tartar for 3D depth
             float shadow = smoothstep(tartarLine - 0.1, tartarLine, vUv.y) * (1.0 - tartarMix);
             finalColor = mix(finalColor, finalColor * 0.3, shadow * 0.8);

             gl_FragColor = vec4(finalColor, alpha);
          }
        `}
      />
    </mesh>
  );
}

function EndodonticEffect({ activeTreatment }: { activeTreatment?: number | null }) {
  const materialRef = useRef<THREE.ShaderMaterial>(null);
  const meshRef = useRef<THREE.Mesh>(null);

  const erythemaParams = {
    px: 0.0,   
    py: 0.33,  // Upper gums
    pz: -0.84, 
    rx: -0.15,
    s: 0.55    // Focused around the central incisors
  };

  const abscessParams = {
    px: 0.09,  
    py: 0.34,  // On the upper right gum
    pz: -0.83, 
    rx: -0.2,
    s: 0.06    
  };

  const cariesParams = {
    px: -0.06,  
    py: 0.24,  // Top of the left incisor, near gum
    pz: -0.86,  
    rx: -0.1,
    s: 0.05    // Size of the physical cup
  };

  // Create deformed geometry for the abscess to make it organic and merged
  const abscessGeo = useMemo(() => {
    const geo = new THREE.SphereGeometry(1, 32, 32);
    const pos = geo.attributes.position;
    for (let i = 0; i < pos.count; i++) {
       const y = pos.getY(i);
       // Flatten the base aggressively so it blends into the gum
       if (y < -0.15) {
         pos.setY(i, -0.15);
       }
    }
    geo.computeVertexNormals();
    return geo;
  }, []);

  useFrame((state, delta) => {
    if (!materialRef.current || !meshRef.current) return;
    const targetOpacity = activeTreatment === 2 ? 1.0 : 0; 
    
    // Smoothly animate opacity
    materialRef.current.uniforms.uOpacity.value = THREE.MathUtils.lerp(
      materialRef.current.uniforms.uOpacity.value,
      targetOpacity,
      delta * 5
    );
    
    // Apply opacity to ALL descendant meshes
    meshRef.current.traverse(child => {
      if (child instanceof THREE.Mesh) {
        if (child.material instanceof THREE.MeshPhysicalMaterial) {
          // Fade transmission and opacity for the SSS material
          child.material.opacity = materialRef.current!.uniforms.uOpacity.value;
          child.material.transmission = 0.6 * materialRef.current!.uniforms.uOpacity.value;
        }
        if (child.material instanceof THREE.MeshStandardMaterial) {
          child.material.opacity = materialRef.current!.uniforms.uOpacity.value;
        }
        if (child.material instanceof THREE.ShaderMaterial && child.material.uniforms.uOpacity) {
          child.material.uniforms.uOpacity.value = materialRef.current!.uniforms.uOpacity.value;
        }
      }
    });

    meshRef.current.visible = materialRef.current.uniforms.uOpacity.value > 0.01;
  });

  return (
    <group ref={meshRef} visible={false}>
      {/* 1. Gum Inflammation (Erythema) - NORMAL BLENDING WITH ALPHA FALLOFF */}
      <mesh 
        position={[erythemaParams.px, erythemaParams.py, erythemaParams.pz]} 
        rotation={[erythemaParams.rx, 0, 0]} 
        scale={erythemaParams.s} 
      >
        <planeGeometry args={[1, 0.7, 32, 32]} />
        <shaderMaterial 
          ref={materialRef} 
          transparent
          depthWrite={false}
          polygonOffset
          polygonOffsetFactor={-8}
          side={THREE.DoubleSide}
          uniforms={{
            uOpacity: { value: 0 }
          }}
          vertexShader={`
            varying vec2 vUv;
            void main() {
              vUv = uv;
              gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
            }
          `}
          fragmentShader={`
            varying vec2 vUv;
            uniform float uOpacity;
            
            void main() {
              vec2 center = vec2(0.5, 0.5);
              vec2 scaledUv = vec2(vUv.x, vUv.y * 1.5 - 0.25);
              float dist = distance(scaledUv, center);
              
              // Deep red core spreading to slightly lighter red
              vec3 coreRed = vec3(0.6, 0.0, 0.05); 
              vec3 edgeRed = vec3(0.8, 0.1, 0.15);
              vec3 color = mix(coreRed, edgeRed, smoothstep(0.1, 0.4, dist));
              
              // Alpha falloff completely to 0 at the edges so no white box appears
              float alpha = smoothstep(0.45, 0.1, dist) * 0.7 * uOpacity;
              
              gl_FragColor = vec4(color, alpha);
            }
          `}
        />
      </mesh>

      {/* 2. The Pus Abscess (Gingival Parulis) - SSS MATERIAL */}
      <mesh
        geometry={abscessGeo}
        position={[abscessParams.px, abscessParams.py, abscessParams.pz]}
        rotation={[abscessParams.rx, 0, 0]}
        scale={[abscessParams.s, abscessParams.s * 0.8, abscessParams.s * 0.4]} // Organic blister
      >
        <meshPhysicalMaterial 
          color="#fff8dc" // Cornsilk/Pale yellowish
          roughness={0.12} // Moist/wet blister
          metalness={0.0}
          transmission={0.6} // Glass/flesh-like transparency (Subsurface effect)
          thickness={0.5}    // Volume thickness for SSS
          ior={1.4}          // Index of refraction for organic tissue
          transparent={true}
          opacity={0.0}
        />
      </mesh>

      {/* 3. Deep Caries (Physical Concave Cup & Jagged Crack) */}
      <group position={[cariesParams.px, cariesParams.py, cariesParams.pz]} rotation={[cariesParams.rx, 0, 0]}>
        {/* The true hollow cup (Hemisphere rendered inside-out) */}
        <mesh rotation={[-Math.PI / 2.5, 0, 0]} scale={cariesParams.s}>
          {/* Swept hemisphere to form a cup */}
          <sphereGeometry args={[1, 32, 16, 0, Math.PI * 2, 0, Math.PI / 2]} />
          <meshStandardMaterial 
            color="#050200" // Pitch black/deep brown void
            side={THREE.BackSide} // Render on the inside to create optical depth illusion
            roughness={0.9}
            transparent={true}
            opacity={0}
            polygonOffset
            polygonOffsetFactor={-9} // Prevent z-fighting with tooth
          />
        </mesh>
        
        {/* The jagged crack extending downwards from the cup */}
        <mesh position={[0, -0.05, 0.01]} scale={0.18}>
          <planeGeometry args={[1, 1, 16, 16]} />
          <shaderMaterial
            transparent
            depthWrite={false}
            polygonOffset
            polygonOffsetFactor={-10}
            side={THREE.DoubleSide}
            uniforms={{ uOpacity: { value: 0 } }}
            vertexShader={`
              varying vec2 vUv;
              void main() {
                vUv = uv;
                gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
              }
            `}
            fragmentShader={`
              varying vec2 vUv;
              uniform float uOpacity;
              void main() {
                // Jagged crack logic
                float crackX = vUv.x - 0.5;
                crackX += sin(vUv.y * 15.0) * 0.02 + cos(vUv.y * 30.0) * 0.01;
                
                // Taper thickness
                float thickness = mix(0.12, 0.0, vUv.y);
                float crack = 1.0 - smoothstep(thickness - 0.01, thickness + 0.01, abs(crackX));
                
                // Top hole blend
                float topHole = smoothstep(0.8, 1.0, vUv.y) * (1.0 - smoothstep(0.0, 0.2, abs(vUv.x - 0.5)));
                crack = max(crack, topHole);
                
                // Colors
                vec3 crackColor = mix(vec3(0.2, 0.1, 0.0), vec3(0.02, 0.0, 0.0), crack);
                
                // Tooth darkening halo
                float dist = distance(vUv, vec2(0.5, 0.8));
                float halo = smoothstep(0.4, 0.1, dist) * 0.5;
                float finalAlpha = max(crack, halo) * uOpacity;
                
                gl_FragColor = vec4(crackColor, finalAlpha);
              }
            `}
          />
        </mesh>
      </group>
    </group>
  );
}

type ActionName = 'Eating' | 'Open-Close' | 'Static'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_7: THREE.SkinnedMesh
    GLTF_created_0_rootJoint: THREE.Bone
  }
  materials: {
    Mouth: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
};

export function Model({ activeTreatment, ...props }: React.JSX.IntrinsicElements['group'] & { activeTreatment?: number | null }) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/mouth.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)


  React.useEffect(() => {
    const action = actions['Open-Close'];
    if (action) {
      action.play();
      action.paused = true;
      action.time = 0;
    }
  }, [actions])

  useFrame((state, delta) => {
    const action = actions['Open-Close'];
    if (action) {
      const isOpen = activeTreatment !== null && activeTreatment !== undefined;
      // The animation is named "Open-Close". The midpoint is where the mouth is fully open.
      const targetTime = isOpen ? action.getClip().duration / 2 : 0; 
      action.time = THREE.MathUtils.damp(action.time, targetTime, 4, delta);
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      {/* 
        NOTE: Disease Shaders have been removed! 
        The mouth is now completely clean and pristine for AI screenshots.
      */}

      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={2.282}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Armature_12">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Mouth_Low_11" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} skeleton={nodes.Object_7.skeleton}>
                    <meshPhysicalMaterial 
                      map={materials.Mouth.map}
                      color={materials.Mouth.color}
                      normalMap={materials.Mouth.normalMap}
                      roughness={0.3} // Thoda badhaya taaki plastic jaisa na lage
                      metalness={0.1}
                      clearcoat={0.5} // Thoda kam kiya taaki safed chamak zyada na aaye
                    />
                  </skinnedMesh>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mouth.glb')